### ISSUE TITLE
Error locating config.py

### ISSUE THREAD

**Issue by fhavio** [mtoensing/Docker-Minecraft-Overviewer#2]
Hello,

I have install this overviewer version by your docker everything went fine until i run your command to render.

I'm running like this

docker run --rm 
-v [world-directory]:/tmp/world/:ro 
-v [config.py-directory]:/tmp/config/:ro 
-v [render-directory]:/tmp/export/:rw -it marctv/overviewer113

in return i get this
"The settings file you specified ('/tmp/config/config.py') does not exist, or is not a file"

I search for the tmp folder and they werent there, so i create them to force, but the error keeps.
Also copy the file config.py to the tmp folder and nothing.

Can you give me a proper command example maybe i'm making something wrong
Hope you can help

**Comment by mtoensing** [comment]
Hi, 
maybe wrong permissons? The config.py directory should contain only a valid overviewer config.py with read permissons for docker.

**Comment by fhavio** [comment]
Hi there thanks for comment, i'm executing the command below

docker run --rm \
  -v /home/jspanos/overviewer/seraphicraft113/world/:/tmp/world/:ro \
  -v /var/www/html/overviewerconfig/config.py:/tmp/config/:ro \
  -v /var/www/html/overviewer113/:/tmp/export/:rw -it marctv/overviewer113

I have full permission (777) on the overviewerconfig folder and file. i run it again and now i'm getting this

> Error response from daemon: OCI runtime create failed: container_linux.go:344: starting container process caused "process_linux.go:424: container init caused \"rootfs_linux.go:58: mounting \\\"/var/www/html/overviewerconfig/config.py\\\" to rootfs \\\"/var/lib/docker/overlay2/68d6883b6212535e6caa9be78bbb1c20b0eac9ae7e20faf791203478d6063807/merged\\\" at \\\"/var/lib/docker/overlay2/68d6883b6212535e6caa9be78bbb1c20b0eac9ae7e20faf791203478d6063807/merged/tmp/config\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type.

**Comment by mtoensing** [comment]
> -v /var/www/html/overviewerconfig/config.py:/tmp/config/:ro

should be: 
-v /var/www/html/overviewerconfig/:/tmp/config/:ro

**Comment by fhavio** [comment]
Thanks just notice it before you comment :)

Now is complaining about the level.dat (already checked the permissions and is 777 (just to be sure))

docker run --rm   -v /home/jspanos/overviewer/seraphicraft113/world/:/tmp/world/:ro   -v /var/www/html/overviewerconfig/:/tmp/config/:ro   -v /var/www/html/overviewer113/:/tmp/export/:rw -it marctv/overviewer113

2019-02-05 11:03:08 E An error was encountered with your configuration.
2019-02-05 11:03:08 E No level.dat file in '/home/jspanos/overviewer/seraphicraft113/world'. Are you sure you have the right path?

Dont know if it's a major factor, but this world has been updated from 1.12.2 to 1.13.2

![image](https://user-images.githubusercontent.com/26770387/52270651-7ee01480-2939-11e9-9ecb-4110abaca75f.png)

Note: i close the issue now i cant reopen :p
